name: Build Chaquopy Wheel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython

      - name: Download and set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          export ANDROID_HOME=$PWD/cmdline-tools/latest
          export PATH=$ANDROID_HOME/bin:$PATH
          yes | $ANDROID_HOME/bin/sdkmanager --licenses > /dev/null

      - name: Download and set up Android NDK r21e
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r21e
          export PATH=$ANDROID_NDK_HOME:$PATH

      - name: Clone Chaquopy build-wheel tool
        run: |
          git clone https://github.com/chaquo/chaquopy.git
          ls -la chaquopy/server/pypi  # Debug: Check directory structure

      - name: Download Chaquopy target
        run: |
          cd chaquopy/server/pypi
          wget https://github.com/chaquo/chaquopy/releases/download/v3.8.18-0/target-3.8.18-0.zip
          unzip -q target-3.8.18-0.zip -d target

      - name: Install additional tools
        run: |
          sudo apt-get update
          sudo apt-get install -y patch patchelf

      - name: Build Wheel for Chaquopy
        run: |
          cd chaquopy/server/pypi
          ./build-wheel.py --python 3.8 --abi armeabi-v7a fastText  # Adjust ABI and package name as needed
          ./build-wheel.py --python 3.8 --abi arm64-v8a fastText  # Build for other ABIs

      - name: Rename Wheel files
        run: |
          cd chaquopy/server/pypi/dist
          mv *.whl ../whl/  # Move generated .whl files to whl directory
          cd ../whl
          for file in *.whl; do
            mv "$file" "${file/linux_android/linux}"  # Modify platform tag to linux_armv7l or linux_aarch64
          done

      - name: Commit and push Wheel files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add whl/
          git commit -m "Update Chaquopy wheel files" || echo "No changes to commit"
          git push origin main
