name: Build FastText Wheel
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cython
 
    - name: Clone and build FastText
      run: |
        git clone https://github.com/facebookresearch/fastText.git
        cd fastText
        pip wheel .  # 构建wheel
 
    - name: Find and upload wheel file
      run: |
        WHEEL_FILE=$(find /tmp/pip-ephem-wheel-cache-* -name "*.whl" | head -n 1)
        echo "Found wheel file: $WHEEL_FILE"
        cp $WHEEL_FILE fasttext_wheel.whl
    
    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fasttext-wheel
        path: fasttext_wheel.whl
