name: Build FastText Wheel
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cython
 
    - name: Clone and build FastText
      run: |
        git clone https://github.com/facebookresearch/fastText.git
        cd fastText
        pip wheel .  # 构建wheel
 
    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fasttext-wheel
        path: /tmp/pip-ephem-wheel-cache-qzn3frth/wheels/35/4e/53/47622083e71bb27656dffd9190cbbb98058bb154d053bb0835/*.whl  # 修改为相对路径，从当前目录（fastText）下的dist文件夹中查找
