name: Build FastText Wheel for Android

on:
  push:
    branches: [ "main" ]  # 推送代码到 main 分支时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取仓库代码

    - name: Setup NDK
      run: |
        # 下载 Android NDK r21e
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        rm android-ndk-r21e-linux-x86_64.zip
        echo "NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r21e" >> $GITHUB_ENV

    - name: Build Wheel
      run: |
        # 添加执行权限并运行编译脚本
        chmod +x build.sh
        ./build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fasttext-wheels  # 产物名称
        path: output/*.whl     # 上传生成的 Wheel 文件
