name: Build FastText Wheel
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # 根据需要选择合适的Python版本
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cython  # 安装构建fasttext所需的依赖
 
    - name: Clone and build FastText
      run: |
        git clone https://github.com/facebookresearch/fastText.git
        cd fastText
        pip wheel .  # 构建wheel文件
 
    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fasttext-wheel
        path: fastText/dist/*.whl
